# Generated by Django 3.1.5 on 2021-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profil_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile'),
        ),
    ]
